---
# Play

- hosts: role_hosting
  tasks:

  ##A2 Install Apache & php7.4

    - name: Install apache2 
      apt: 
        name: apache2
        state: present
    - name: Install
      apt:
        name: php7.3
        state: present
        
