---
# Play

- hosts: role_hosting
  tasks:

  ##A2 Install Apache & php7.4

    - name: Install apache2 
      apt: 
        name: apache2
        state: present
    - name: Install
      apt:
        name: php7.3
        state: present
        
  ## A3 Download Dokuwiki

    - name: Dokuwiki check 
      stat:
        path: /usr/src/dokuwiki
      register: dokuwiki_directory

    - name: Download dokuwiki
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src
      when: not dokuwiki_directory.stat.exists or not dokuwiki_directory.stat.isdir

  ## A4 Unzip Dokuwiki

    - name: Unzip dokuwiki
      unarchive:
        remote_src: yes 
        src: /usr/src/dokuwiki-stable.tgz
        dest: /usr/src
      when: not dokuwiki_directory.stat.exists or not dokuwiki_directory.stat.isdir

    - name: Rename dokuwiki 2020-07-29 directory to dokuwiki 
      command: mv /usr/src/dokuwiki-2020-07-29 /usr/src/dokuwiki
      when: not dokuwiki_directory.stat.exists or not dokuwiki_directory.stat.isdir