---
# Play

- hosts: role_hosting
  tasks:
    - name: Install apache2 
      apt: 
        name: apache2
        state: present
    - name: update & upgrade
      apt: 
        upgrade: dist
        cache: yes
    - name: PHP | ADD php repo
      apt_repository:
        repo: "ppa:ondrej/php"

    - name: PHP | Install
      apt:
        update_cache: yes
        name:
          - "php7.4"
