---
# Play

- hosts: role_hosting
  tasks:

  ##A2 Install Apache & php7.3

    - name: Install apache2 
      apt: 
        name: apache2
        state: present
    - name: Install
      apt:
        name: php7.3
        state: present
        
  ## A3 Download Dokuwiki

    - name: Check dokuwiki is already installed
      stat:
        path: /usr/src/dokuwiki
      register: dokuwiki_directory

    - name: Download dokuwiki
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src

  ## A4 Unzip Dokuwiki

    - name: Unzip dokuwiki
      unarchive:
        remote_src: yes 
        src: /usr/src/dokuwiki-stable.tgz
        dest: /usr/src
      when: dokuwiki_directory.stat.exists and not dokuwiki_directory.stat.isdir

    - name: Rename dokuwiki 2020-07-29 directory to dokuwiki 
      command: mv /usr/src/dokuwiki-2020-07-29 /usr/src/dokuwiki
      when: dokuwiki_directory.stat.exists and not dokuwiki_directory.stat.isdir

  ## A5 Virtualhosts
    - name: Create 2 virtualhosts 
      copy:
        src: files/{{ item }}
        dest: /etc/apache2/sites-available/{{ item }}
      with_items:
        - recettes-wiki.conf
        - politique-wiki.conf
